routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'home'], function(){
    Route::get('/', 'HomeController@index');
    Route::get('/news', 'HomeController@news');
    Route::get('/league/{slug}', 'HomeController@newsleague');
    Route::get('/{slug}/lich-thi-dau', 'HomeController@schedule');
    Route::post('/{slug}/lich-thi-dau', 'HomeController@scheduleAjax')->name('lichThiDau');
    Route::get('/{slug}/ket-qua-thi-dau', 'HomeController@match');
    Route::post('/{slug}/ket-qua-thi-dau', 'HomeController@matchAjax')->name('ketQuaThiDau');
    Route::get('/{slug}/bang-xep-hang', 'HomeController@rank');
    Route::get('news-detail/id-{id}', 'HomeController@viewNews');
    Route::get('/search', 'HomeController@search');
});






Route::group(['prefix'=>'admin','middleware'=>'auth', 'namespace'=>'admin'], function(){
    Route::get('dashboard', 'adminController@dashboard');
    Route::resource('season', 'SeasonController');
    Route::resource('league', 'LeagueController');
    Route::resource('news', 'NewsController');
    Route::resource('competion', 'CompetionController');
    Route::resource('group', 'GroupController');
    Route::resource('round', 'RoundController');
    Route::resource('team', 'TeamController');
    Route::resource('player', 'PlayerController');
    Route::resource('match', 'MatchController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('squad', 'SquadController');
});



Auth::routes(['register']);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Match.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Match extends Model
{
    protected $table = 'matchs';
    protected $fillable = ['id','play_at','play_time','score1','score2','round_id','group_id','team1_id','team2_id'];
    public function team1()
    {
        return $this->belongsTo('App\Team', 'team1_id');
    }
    public function team2()
    {
        return $this->belongsTo('App\Team', 'team2_id');
    }
    public function matchround()
    {
        return $this->belongsTo('App\Round', 'round_id');
    }
    public function matchgroup()
    {
        return $this->belongsTo('App\Group', 'group_id');
    }
}

app/Http/Controllers/admin/MatchController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\FormMatch;
use App\Match;
use App\Round;
use App\Group;
use App\Team;


class MatchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $matches = Match::paginate(15);
        return view('admin.match.index',compact('matches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rounds = Round::all();
        $team1 = Team::all();
        $team2 = Team::all();
        $groups = Group::all();
        return view('admin.match.create',compact('rounds', 'groups','team1','team2'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormMatch $request)
    {
        
        $data = new Match;
        $data->play_at = $request->play_at;
        $data->play_time = $request->play_time;
        $data->round_id = $request->round_id;
        if($data->group_id)
        $data->group_id = $request->group_id;
        else $data->group_id = null;
        $data->team1_id = $request->team1_id;
        $data->team2_id = $request->team2_id;
        $data->score2 = $request->score2;
        $data->score1 = $request->score1;
        $data->save();
        return redirect('admin/match');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $match = Match::findOrFail($id);
        $rounds = Round::all();
        $team1 = Team::all();
        $team2 = Team::all();
        $groups = Group::all();
        return view('admin.match.edit',compact('match','rounds','team1','team2','groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FormMatch $request, $id)
    {
        $data = [];
        $match = Match::findOrFail($id);
        $data['play_at'] = $request->play_at;
        $data['play_time'] = $request->play_time;
        $data['round_id'] = $request->round_id;
        if($request->group_id)
        $data['group_id'] = $request->group_id;
        else $data['group_id'] = null;
        $data['score1'] = $request->score1;
        $data['score2'] = $request->score2;
        $data['team1_id'] = $request->team1_id;
        $data['team2_id'] = $request->team2_id;
       
        if ($match->update($data)) {
            return redirect('/admin/match');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $match = Match::find($id)->delete();
        return redirect('/admin/match');
    }
}

resources/views/admin/match/create.blade.php
@extends('admin.layouts.master')
@section('title','match')
 @section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Tạo trận đấu</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('match.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="at">Play at</label>
                                    <input type="text" class="form-control" id="at" name="play_at" placeholder="Play at" >
                                    {{showErrors($errors, 'play_at')}}</div>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Play time</span>
                                    </div>
                                    <input type="datetime-local" class="form-control" data-inputmask-alias="datetime" name="play_time" >
                                    {{showErrors($errors, 'play_time')}}</div>
                                <div class="form-group">
                                    <label>Round</label>
                                    <select class="form-control" name="round_id" >
                                        @foreach($rounds as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'round_id')}}</div>
                                <div class="form-group">
                                    <label>Group</label>
                                    <select class="form-control" name="group_id">
                                        <option></option>
                                        @foreach($groups as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'group_id')}}</div>
                                <div class="form-group">
                                    <label>Team1</label>
                                    <select class="form-control" name="team1_id" >
                                        @foreach($team1 as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'team1_id')}}</div>
                                <div class="form-group">
                                    <label for="sc1">Score1</label>
                                    <input type="text" class="form-control" id="sc1" name="score1" placeholder="Score1" >
                                    {{showErrors($errors, 'score1')}}</div>
                                <div class="form-group">
                                    <label>Team2</label>
                                    <select class="form-control" name="team2_id" >
                                        @foreach($team2 as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'team2_id')}}</div>
                                <div class="form-group">
                                    <label for="sc2">Score2</label>
                                    <input type="text" class="form-control" id="sc2" name="score2" placeholder="Score2" >
                                    {{showErrors($errors, 'score2')}}</div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
@endsection

resources/views/admin/match/edit.blade.php
@extends('admin.layouts.master')@section('title','match') @section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Sửa Match</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="admin/match/{{ $match->id }}">
                            @method('PATCH') @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="at">Play at</label>
                                    <input type="text" class="form-control" id="at"  name="play_at" placeholder="Play at" value="{{ old('play_at',$match->play_at ?? '') }}">
                                    {{showErrors($errors, 'play_at')}}</div>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Play in</span>
                                    </div>
                                    <input type="datetime-local" class="form-control" data-inputmask-alias="datetime" name="play_time">
                                    {{showErrors($errors, 'play_time')}}</div>
                                <div class="form-group">
                                    <label>Round</label>
                                    <select class="form-control" name="round_id">
                                        @foreach($rounds as $item)
                                        <option value="{{$item->id}}" @if ($item->id == old('round_id', $match->round_id))selected="selected"@endif>{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'round_id')}}</div>
                                <div class="form-group">
                                    <label>Group</label>
                                    <select class="form-control" name="group_id">
                                        <option></option>
                                        @foreach($groups as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'group_id')}}</div>
                                <div class="form-group">
                                    <label>Team1</label>
                                    <select class="form-control" name="team1_id">
                                        @foreach($team1 as $item)
                                        <option value="{{$item->id}}" @if ($item->id == old('team1_id', $match->team1_id))selected="selected"@endif>{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'team1_id')}}</div>
                                <div class="form-group">
                                    <label for="sc1">Score1</label>
                                    <input type="text" class="form-control" id="sc1" name="score1" value="{{ old('score1',$match->score1 ?? '') }}">
                                    {{showErrors($errors, 'score1')}}</div>
                                <div class="form-group">
                                    <label>Team2</label>
                                    <select class="form-control" name="team2_id">
                                        @foreach($team2 as $item)
                                        <option value="{{$item->id}}" @if ($item->id == old('team2_id', $match->team2_id))selected="selected"@endif>{{$item->name}}</option>
                                        @endforeach

                                    </select>
                                    {{showErrors($errors, 'team2_id')}}</div>
                                <div class="form-group">
                                    <label for="sc2">Score2</label>
                                    <input type="text" class="form-control" id="sc2" name="score2" value="{{ old('score2',$match->score2 ?? '') }}">
                                    {{showErrors($errors, 'score2')}}</div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
</form>
                    </div>
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
@endsection

resources/views/admin/match/index.blade.php
@extends('admin.layouts.master')
@section('title','match')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Matches</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Match</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
            <a href="{{ route('match.create') }}"><button class="btn btn-primary">Thêm mới</button></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Play at</th>
                  <th>Play time</th>
                  <th>Round</th>
                  <th>Group</th>
                  <th>Team1</th>
                  <th>Score1</th>
                  <th>Team2</th>
                  <th>Score2</th>
                  <th>Delete</th>
                  <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($matches as $key => $item)
                <tr>
                  <td>{{ ++$key }}</td>
                  <td>{{ $item->play_at }}</td>
                  <td>{{ Carbon\Carbon::parse($item->play_time)->isoFormat('MMMM Do YYYY, h:mm:ss a') }}</td>
                  <td>{{ $item->matchround->name }}</td>
                  <td>{{ $item->matchgroup }}</td>
                  <td>{{ $item->team1->name }}</td>
                  <td>{{ $item->score1 }}</td>
                  <td>{{ $item->team2->name }}</td>
                  <td>{{ $item->score2 }}</td>
                  <td>
                    <form action="/admin/match/{{ $item->id }}" method="POST">
                        @csrf 
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </form>
                  </td>
                  <td><a href="{{ url('/admin/match/'. $item->id .'/edit') }}"><button class="mt-1 btn btn-primary">edit</button></a></td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <div class="row">
        <div class="col-md-12">
            {{$matches->links()}}
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
   
@endsection