routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'home'], function(){
    Route::get('/', 'HomeController@index');
    Route::get('/news', 'HomeController@news');
    Route::get('/league/{slug}', 'HomeController@newsleague');
    Route::get('/{slug}/lich-thi-dau', 'HomeController@schedule');
    Route::post('/{slug}/lich-thi-dau', 'HomeController@scheduleAjax')->name('lichThiDau');
    Route::get('/{slug}/ket-qua-thi-dau', 'HomeController@match');
    Route::post('/{slug}/ket-qua-thi-dau', 'HomeController@matchAjax')->name('ketQuaThiDau');
    Route::get('/{slug}/bang-xep-hang', 'HomeController@rank');
    Route::get('news-detail/id-{id}', 'HomeController@viewNews');
    Route::get('/search', 'HomeController@search');
});






Route::group(['prefix'=>'admin','middleware'=>'auth', 'namespace'=>'admin'], function(){
    Route::get('dashboard', 'adminController@dashboard');
    Route::resource('season', 'SeasonController');
    Route::resource('league', 'LeagueController');
    Route::resource('news', 'NewsController');
    Route::resource('competion', 'CompetionController');
    Route::resource('group', 'GroupController');
    Route::resource('round', 'RoundController');
    Route::resource('team', 'TeamController');
    Route::resource('player', 'PlayerController');
    Route::resource('match', 'MatchController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('squad', 'SquadController');
});



Auth::routes(['register']);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Squad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Squad extends Model
{
    protected $table = 'squads';
    protected $fillable = ['id','name','player_id','team_id'];
    public function team()
    {
        return $this->belongsto('App\Team', 'team_id', 'id');
    }
    public function player()
    {
        return $this->belongsto('App\Player', 'player_id', 'id');
    }
}

app/Http/Controllers/admin/SquadController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Squad;
use App\Team;
use App\Player;
use App\Http\Requests\FormSquad;

class SquadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $squads = Squad::all();
        return view('admin.squad.index',compact('squads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $players = Player::all();
        $teams = Team::all();
        return view('admin.squad.create',compact('players','teams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormSquad $request)
    {
        $squad = new Squad;
        
        $squad->pos = $request->pos;
        $squad->team_id = $request->team_id;
        $squad->player_id = $request->player_id;
        $squad->save();
        return redirect('/admin/squad');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $players = Player::all();
        $teams = Team::all();
        $squad = Squad::findOrFail($id);
        return view('admin.squad.edit',compact('players','teams','squad'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FormSquad $request, $id)
    {
        $data = [];
        $squad = Squad::findOrFail($id);
        $data['pos'] = $request->pos;
        $data['player_id'] = $request->player_id;
        $data['team_id'] = $request->team_id;
       

        $squad->update($data);
            return redirect('/admin/squad');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $squad = Squad::find($id)->delete();
        return redirect('/admin/squad');
    }
}

resources/views/admin/squad/create.blade.php
@extends('admin.layouts.master')
@section('title','squad')
@section('content')
<div class="content-wrapper">
	<section class="content-header">
		<div class="container-fluid">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Tạo squad</h3>
						</div>
						<!-- /.card-header -->
						<!-- form start -->
						<form role="form" method="POST" action="{{ route('squad.store') }}">
							@csrf
							<div class="card-body">
								<div class="form-group">
									<label for="pos">Position</label>
									<input type="text" class="form-control" id="pos" name="pos" placeholder="Position">
									{{showErrors($errors, 'pos')}}</div>
								<div class="form-group">
									<label>Team</label>
									<select class="form-control" name="team_id">
										@foreach($teams as $item)
										<option value="{{$item->id}}">{{$item->name}}</option>
										@endforeach
									</select>
									{{showErrors($errors, 'team_id')}}</div>
								<div class="form-group">
									<label>Player</label>
									<select class="form-control" name="player_id">
										@foreach($players as $item)
										<option value="{{$item->id}}">{{$item->name}}</option>
										@endforeach
									</select>
									{{showErrors($errors, 'player_id')}}</div>
							</div>
							<!-- /.card-body -->
							<div class="card-footer">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
				<!--/.col (right) -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</section>
</div>
@endsection

resources/views/admin/squad/edit.blade.php
@extends('admin.layouts.master')
@section('title','squad')
@section('content')
<div class="content-wrapper">
	<section class="content-header">
		<div class="container-fluid">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">Tạo season</h3>
						</div>
						<!-- /.card-header -->
						<!-- form start -->
						<form role="form" method="POST" action="admin/squad/{{ $squad->id }}">
							@method('PATCH')
							@csrf
							<div class="card-body">
								<div class="form-group">
									<label for="pos">Position</label>
									<input type="text" class="form-control" id="pos" name="pos" placeholder="Position">
									{{showErrors($errors, 'pos')}}</div>
								<div class="form-group">
									<label>Team</label>
									<select class="form-control" name="team_id">
										@foreach($teams as $item)
										<option value="{{$item->id}}">{{$item->name}}</option>
										@endforeach
									</select>
									{{showErrors($errors, 'team_id')}}</div>
								<div class="form-group">
									<label>Player</label>
									<select class="form-control" name="player_id">
										@foreach($players as $item)
										<option value="{{$item->id}}">{{$item->name}}</option>
										@endforeach
									</select>
									{{showErrors($errors, 'player_id')}}</div>
							</div>
							<!-- /.card-body -->
							<div class="card-footer">
								<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
				<!--/.col (right) -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</section>
</div>
@endsection

resources/views/admin/squad/index.blade.php
@extends('admin.layouts.master')
@section('title','squad')
@section('content')
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>Squads</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item"><a href="#">Home</a></li>
						<li class="breadcrumb-item active">Squad</li>
					</ol>
				</div>
			</div>
		</div>
		<!-- /.container-fluid -->
	</section>
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<a href="{{ route('squad.create') }}"><button class="btn btn-primary">Add</button></a>
					</div>
					<!-- /.card-header -->
					<div class="card-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Team</th>
									<th>Position</th>
									<th>Delete</th>
									<th>Edit</th>
								</tr>
							</thead>
							<tbody>
								@foreach($squads as $key => $item)
								<tr>
									<td>{{ ++$key }}</td>
									<td>{{ $item->player->name }}</td>
									<td>{{ $item->team->name }}</td>
									<td>{{ $item->pos }}</td>
									<td>
										<form action="/admin/squad/{{ $item->id }}" method="POST">
											@csrf 
											@method('DELETE')
											<button type="submit" class="btn btn-primary">Delete</button>
										</form>
									</td>
									<td><a href="{{ url('/admin/squad/'. $item->id .'/edit') }}"><button class="mt-1 btn btn-primary">edit</button></a></td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</section>
	<!-- /.content -->
</div>
@endsection