routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'home'], function(){
    Route::get('/', 'HomeController@index');
    Route::get('/news', 'HomeController@news');
    Route::get('/league/{slug}', 'HomeController@newsleague');
    Route::get('/{slug}/lich-thi-dau', 'HomeController@schedule');
    Route::post('/{slug}/lich-thi-dau', 'HomeController@scheduleAjax')->name('lichThiDau');
    Route::get('/{slug}/ket-qua-thi-dau', 'HomeController@match');
    Route::post('/{slug}/ket-qua-thi-dau', 'HomeController@matchAjax')->name('ketQuaThiDau');
    Route::get('/{slug}/bang-xep-hang', 'HomeController@rank');
    Route::get('news-detail/id-{id}', 'HomeController@viewNews');
    Route::get('/search', 'HomeController@search');
});






Route::group(['prefix'=>'admin','middleware'=>'auth', 'namespace'=>'admin'], function(){
    Route::get('dashboard', 'adminController@dashboard');
    Route::resource('season', 'SeasonController');
    Route::resource('league', 'LeagueController');
    Route::resource('news', 'NewsController');
    Route::resource('competion', 'CompetionController');
    Route::resource('group', 'GroupController');
    Route::resource('round', 'RoundController');
    Route::resource('team', 'TeamController');
    Route::resource('player', 'PlayerController');
    Route::resource('match', 'MatchController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('squad', 'SquadController');
});



Auth::routes(['register']);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/League.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str; 
class League extends Model
{
    protected $table = 'leagues';
    protected $fillable = ['id','slug',
       'name'
    ];
    public function competion()
    {
        return $this->hasMany('App\Competion', 'league_id', 'id');
    }
    public function news()
    {
        return $this->hasMany('App\News', 'league_id');
    }
    public function getSlug($name) {
        
        return Str::slug($name);
    }
}

app/Http/Controllers/Api/LeagueController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\League;
use App\Http\Resources\League as LeagueRource;
use App\Http\Resources\LeagueCollection;

class LeagueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return League::all();
       // return LeagueRource::collection(League::all());
        return new LeagueCollection(League::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return League::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(League $league)
    {
        return $league;
       // return new LeagueRource($league);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, League $league)
    {
        $league->update($request->all());
        return $league;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(League $league)
    {
        $league->delete();
    }
}

app/Http/Controllers/admin/LeagueController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\League;
use App\Http\Requests\Formleague;

class LeagueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $leagues = League::all();
        return view('admin.league.index',compact('leagues'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.league.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Formleague $request)
    {
        $data = new League;
        $data->name = $request->name;
        $data->slug = $data->getSlug($request->name);

        $data->save();
        return redirect('/admin/league');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = League::select('id', 'name','slug')->get()->toArray();
        $league = League::findOrFail($id);
        return view('admin.league.edit', compact('league', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Formleague $request, $id)
    {
        $league = League::findOrFail($id);
        $data = [];
        $data['name'] = $request->name;
        $data['slug'] = $league->getSlug($request->name);
        

        if ($league->update($data)) {
            return redirect('/admin/league');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $league = League::find($id)->delete();
        return redirect('/admin/league');
    }
}

resources/views/admin/league/create.blade.php
@extends('admin.layouts.master')
@section('title','league')
@section('content')
<div class="content-wrapper">
<section class="content-header">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Tạo season</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="{{ route('league.store') }}">
              @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name" >
                    {{showErrors($errors, 'name')}}</div>
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    </div>
@endsection     

resources/views/admin/league/edit.blade.php
@extends('admin.layouts.master')
@section('title','league')
@section('content')
<div class="content-wrapper">
<section class="content-header">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Tạo league</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="POST" action="admin/league/{{ $league->id }}">
              @method('PATCH')
              @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name',$league->name ?? '') }}" required>
                    {{showErrors($errors, 'name')}}</div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    </div>
@endsection     

resources/views/admin/league/index.blade.php
@extends('admin.layouts.master')
@section('title','league')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Leagues</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">League</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
            <a href="{{ route('league.create') }}"><button class="btn btn-primary">Thêm mới</button></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Slug</th>
                  <th>Delete</th>
                  <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($leagues as $key => $item)
                <tr>
                  <td>{{ ++$key }}</td>
                  <td>{{ $item->name }}</td>
                  <td>{{ $item->slug }}</td>
                  <td>
                  <form action="/admin/league/{{ $item->id }}" method="POST">
										@csrf 
										@method('DELETE')
										<button type="submit" class="btn btn-primary">Delete</button>
									</form>
                  </td>
                  <td><a href="{{ url('/admin/league/'. $item->id .'/edit') }}"><button class="mt-1 btn btn-primary">Edit</button></a></td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
   
@endsection