routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'home'], function(){
    Route::get('/', 'HomeController@index');
    Route::get('/news', 'HomeController@news');
    Route::get('/league/{slug}', 'HomeController@newsleague');
    Route::get('/{slug}/lich-thi-dau', 'HomeController@schedule');
    Route::post('/{slug}/lich-thi-dau', 'HomeController@scheduleAjax')->name('lichThiDau');
    Route::get('/{slug}/ket-qua-thi-dau', 'HomeController@match');
    Route::post('/{slug}/ket-qua-thi-dau', 'HomeController@matchAjax')->name('ketQuaThiDau');
    Route::get('/{slug}/bang-xep-hang', 'HomeController@rank');
    Route::get('news-detail/id-{id}', 'HomeController@viewNews');
    Route::get('/search', 'HomeController@search');
});






Route::group(['prefix'=>'admin','middleware'=>'auth', 'namespace'=>'admin'], function(){
    Route::get('dashboard', 'adminController@dashboard');
    Route::resource('season', 'SeasonController');
    Route::resource('league', 'LeagueController');
    Route::resource('news', 'NewsController');
    Route::resource('competion', 'CompetionController');
    Route::resource('group', 'GroupController');
    Route::resource('round', 'RoundController');
    Route::resource('team', 'TeamController');
    Route::resource('player', 'PlayerController');
    Route::resource('match', 'MatchController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('squad', 'SquadController');
});



Auth::routes(['register']);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Round.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
    
class Round extends Model
{
    protected $table = 'rounds';
    protected $fillable = ['id','name','active','display','stt'];
    public function schedule()
    {
        return $this->hasMany('App\Schedule', 'round_id');
    }

 
    public function competion()
    {
        return $this->belongsTo('App\Competion', 'competion_id', 'id');
    }
    public function matchround()
    {
        return $this->hasMany('App\Match', 'round_id');
    }
}

app/Http/Controllers/admin/RoundController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Round;
use App\Competion;
use App\Http\Requests\FormRound;

class RoundController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rounds = Round::paginate(38);
        return view('admin.round.index',compact('rounds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rounds = Round::all();
        $competions = Competion::all();
        return view('admin.round.create',compact('rounds','competions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormRound $request)
    {
        $data = new Round;
        $data->name = $request->name;
        $data->display = $request->display;
        $data->competion_id = $request->competion_id;
        if($request->get('active'))
        $data->active = 1;
        else 
        $data->active =  0;
        $data->stt =  $request->stt;

        $data->save();
        return redirect('/admin/round');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $competions = Competion::all();
        $round = Round::findOrFail($id);
        return view('admin.round.edit', compact('competions','round'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FormRound $request, $id)
    {
        $data = [];
        $round = Round::findOrFail($id);
        $data['name'] = $request->name;
        $data['display'] = $request->display;
        $data['competion_id'] = $request->competion_id;
        $data['stt'] =  $request->stt;
        $data['active'] = $request->has('active');
        if ($round->update($data)) {
            return redirect('/admin/round');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $round = Round::find($id)->delete();
        return redirect('/admin/round');
    }
}

resources/views/admin/round/create.blade.php
@extends('admin.layouts.master')
@section('title','round')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Tạo group</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('round.store') }}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                                    {{showErrors($errors, 'name')}}
                                </div>
                                <div class="form-group">
                                    <label for="display">Display</label>
                                    <input type="text" class="form-control" id="display" name="display" placeholder="Display">
                                    {{showErrors($errors, 'name')}}
                                </div>
                                <div class="form-group">
                                    <label>Competion</label>
                                    <select class="form-control" name="competion_id">
                                        @foreach($competions as $key => $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                    {{showErrors($errors, 'competion_id')}}
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="hot" name="active" >
                                    <label class="form-check-label" for="hot"  >Active</label>
                                    {{showErrors($errors, 'active')}}
								</div>
								<div class="form-check">
                                    <label class="form-check-label" for="stt"  >Stt</label>
                                    <input type="text" class="form-control" id="stt" name="stt" >
                                    {{showErrors($errors, 'stt')}}
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
@endsection

resources/views/admin/round/edit.blade.php
@extends('admin.layouts.master')
@section('title','round')
@section('content')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Sửa round</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="admin/round/{{ $round->id }}">
                            @method('PATCH')
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name',$round->name ?? '') }}">
                                    {{showErrors($errors, 'name')}}
                                </div>
                                <div class="form-group">
                                    <label for="display">Display</label>
                                    <input type="text" class="form-control" id="display" name="display" value="{{ old('display',$round->display ?? '') }}">
                                    {{showErrors($errors, 'name')}}
                                </div>
                                <div class="form-group">
                                    <label>Competion</label>
                                    <select class="form-control" name="competion_id">
                                    @foreach($competions as $key => $item)
                                    <option value="{{$item->id}}"
                                    @if ($item->id == old('competion_id', $round->competion_id))selected="selected"@endif
                                    >{{$item->name}}</option>
                                    @endforeach
                                    </select>
                                    {{showErrors($errors, 'competion_id')}}
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="active" name="active" {{ old('active', $round->active) === 1 ? 'checked' : '' }}>
                                    <label class="form-check-label" for="active" >Active</label>
                                    {{showErrors($errors, 'active')}}
								</div>
								<div class="form-check">
                                    <label class="form-check-label" for="stt"  >Stt</label>
                                    <input type="text" class="form-control" id="stt" name="stt" value="{{ old('name',$round->stt ?? '') }}">
                                    {{showErrors($errors, 'stt')}}
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
@endsection

resources/views/admin/round/index.blade.php
@extends('admin.layouts.master')
@section('title','round')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Rounds</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Round</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('round.create') }}"><button class="btn btn-primary">Add</button></a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Display</th>
                                    <th>Competion</th>
                                    <th>Active</th>
                                    <th>Stt</th>
                                    <th>Delete</th>
                                    <th>Edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($rounds as $key => $item)
                                <tr>
                                    <td>{{ ++$key }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->display }}</td>
                                    <td>{{ $item->competion->name }}</td>
                                    <td>{{ $item->active }}</td>
                                    <td>{{ $item->stt }}</td>
                                    <td>
                                        <form action="/admin/round/{{ $item->id }}" method="POST">
                                            @csrf 
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-primary">Delete</button>
                                        </form>
                                    </td>
                                    <td><a href="{{ url('/admin/round/'. $item->id .'/edit') }}"><button class="mt-1 btn btn-primary">edit</button></a></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-md-12">
                {{$rounds->links()}}
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection